# NeuroPETRIX Pre-commit Configuration
# Otomatik kod kalitesi ve hata yakalama

repos:
  # Python kod kalitesi
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88, --target-version=py38]

  # Import sıralama
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]

  # Linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        args: [--ignore-missing-imports]

  # Güvenlik taraması
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-r, backend/, -f, json, -o, bandit-report.json]
        exclude: ^tests/

  # Environment dosyaları kontrolü
  - repo: local
    hooks:
      - id: env-check
        name: Environment files check
        entry: python scripts/check_env.py
        language: system
        files: \.env.*$
        pass_filenames: false

  # Import hataları kontrolü
  - repo: local
    hooks:
      - id: import-check
        name: Import errors check
        entry: python scripts/check_imports.py
        language: system
        files: \.py$
        pass_filenames: true

  # Logger kullanımı kontrolü
  - repo: local
    hooks:
      - id: logger-check
        name: Logger usage check
        entry: python scripts/check_loggers.py
        language: system
        files: \.py$
        pass_filenames: true

  # JSON dosyaları kontrolü
  - repo: local
    hooks:
      - id: json-check
        name: JSON syntax check
        entry: python -m json.tool
        language: system
        files: \.json$

  # YAML dosyaları kontrolü
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-d, relaxed]

  # Frontend kod kalitesi
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        exclude: ^node_modules/
        additional_dependencies:
          - eslint@^8.0.0
          - "@typescript-eslint/eslint-plugin@^6.0.0"
          - "@typescript-eslint/parser@^6.0.0"

  # Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|md)$
        exclude: ^node_modules/

  # Commit mesaj kontrolü
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

# Global ayarlar
default_stages: [commit, push]
fail_fast: false
minimum_pre_commit_version: 3.0.0