openapi: 3.0.0
info:
  title: HBYS Mock API
  version: 0.1.0
paths:
  /studies:
    get:
      summary: Tarih aralığında çalışma listesi
      parameters:
        - in: query
          name: from
          schema: { type: string }
        - in: query
          name: to
          schema: { type: string }
      responses:
        '200':
          description: OK
  /reports/{study_uid}:
    get:
      summary: Çalışma raporu metni
      parameters:
        - in: path
          name: study_uid
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
